site_name: TCA Data Management Accelerator Documentation Hub
site_url: http://127.0.0.1:8000/
theme:
  name: material
plugins:
  - awesome-pages
markdown_extensions:
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.superfences